### ISSUE TITLE
Submit version 1.0 to CRAN

### ISSUE THREAD

**Issue by sfirke** [sfirke/janitor#140]
Should this be version `1.0`?  It has breaking changes, and I think represents an API paradigm shift with `tabyl`.  Plus honestly, I'm out of big ideas for this package after this, and don't see anything that could merit a 1.0.

To dos before that:

**DONE**

- [x] Build out tabyl vignette (#132) 
- [x] Publicize new tabyl + adorn functionality, solicit demo users to try out the dev version
- [x] Address any other issues like ~~#100~~ , ~~#77~~, ~~#153~~, ~~#168~~ that might be germane to this revision. 
- [x] Review ~~#146~~ #178 
- [x] See if clean_names tests pass for other Windows users - having some weird issues locally
- [x] After next version of `snakecase` goes to CRAN, remove `Remotes:` from DESCRIPTION and add  `snakecase (>= 0.9)` (confirm V number) to Imports
- [x] Create packagedown website
- [x] Process remaining issues, closing and tagging appropriately.
- [x] Run lintr #172
- [x] Update NEWS.Md to describe release
- [x] Bump version to 1.0 in Description and NEWS
- [x] Remove note about "tabyl is not currently not on CRAN" from tabyls vignette & README
- [x] Check that image paths are right per CRAN standards for Index.Rmd - it won't knit

**PENDING**

- [x] Submit!

**AFTER SUBMITTING**

- [ ] Write a blog post publicizing it
- [ ] Tweet, incl. link to pkgdown site
- [x] GitHub release
- [ ] Blogpost?
- [x] Optional tweaks to packagedown site #156 
- [x] Add stable badge to repo

90% of this release is done, now it's the dull stuff.  Must. Wrap. This. Up.

**Comment by sfirke** [comment]
Getting closer...

**Comment by garthtarr** [comment]
I think this is a very worthy 1.0 release! I was just showing off some of the new functionality today to someone and couldn't work out why it wasn't working (they had the CRAN release installed).  My suggestion from your pending list, FWIW, is to 

- [ ] Update NEWS.Md to describe release
- [ ] Bump version to 1.0 in Description and NEWS
- [ ] Submit!

Full disclosure: I want to use it in my teaching for R novices without having to introduce `devtools::install_github(...)` ;)

**Comment by sfirke** [comment]
I really appreciate that, Garth.  I've been haunted by this idea that if I'm calling it 1.0, I should get everything just right.  But I think the functionality is finished, and at this point I'm hurting the user experience by requiring installation from GitHub.  Too much tinkering around the edges.

I hereby vow to submit to CRAN by end of March at the latest!  🥅

**Comment by garthtarr** [comment]
Great news!

**Comment by sfirke** [comment]
I think I'm done with version 1.0.  This update breaks a few CRAN packages that depend on janitor; I may give those maintainers some time to adjust, but otherwise I'm ready to submit what I have on GitHub now.

And then maybe leave this package alone for a little while :stuck_out_tongue_winking_eye:

**Comment by sfirke** [comment]
I submitted this AM 🤞  My previous releases have gotten quick responses, but this is a more complicated cases (it causes WARNINGs for downstream dependencies).  Those cases are addressed in my `cran-comments` but I expect at the very least will take more inspection on the part of CRAN folks.
