### ISSUE TITLE
Upkeep proposition / spring cleaning

### ISSUE THREAD

**Issue by olivroy** [sfirke/janitor#549]
Hi,

I would have a couple suggestions to improve janitor

Let me know what you think and I can open PRs for the things you think are relevant!

* [x] Improve documentation
  *  Use `Roxygen: list(markdown = TRUE)` in `DESCRIPTION` to simplify the documentation (#551)
  *  (i.e. remove unnecessary explicit tags `@title`, `@description` etc. , `\{code}` and (#551)
  *  improve cross-references with `[fun]`  (#559) 
  * Use `@inheritParams` to avoid doc duplication (TODO later)
  * See https://r-pkgs.org/man.html
* [ ] Improve error, warnings and messages (use ~~`rlang::abort()`~~ or `cli::cli_abort()`and ~~use more snapshot tests to capture them~~ https://style.tidyverse.org/error-messages.html (#560)
* [x] Remove tidyr superseded functions (gather spread) (#552)

Edit:

* [x] Remove docs/ (#550)
* [x] Add favicon to the package website https://pkgdown.r-lib.org/reference/build_favicons.html (rename logo_small.png to logo.png) <https://r-pkgs.org/website.html#logo>. Retrieved .svg [here](https://github.com/maxogden/hexbin/blob/7a67b003156ccb8b20d46acfe72e1c507104eb25/vector/janitor.svg) #553 
* [x] Remove references to master branch (in README for example) (#551)
* [ ] Edit `_pkgdown.yml` so that functions are organized on the site https://sfirke.github.io/janitor/reference/index.html (see https://dplyr.tidyverse.org/reference/index.html for an example) 
* [x] Add `@keywords internal` to make sure hard deprecated functions don't show up in the package reference (#551)
* [x] Remove `index.md` and make README.md to website homepage (#554)

**Comment by billdenney** [comment]
Thanks for this help!

I like all of this except for the snapshot tests.  I don't prefer snapshot tests because they don't fail on CRAN.  I prefer explicit tests for messages with regular expressions or specific examples so that we always know that we are testing exactly what we intend to test.

For the error messages, I'd prefer using `rlang` rather than `cli` since we already depend on `rlang` (even though I like the `cli` visuals better).

I definitely think we should remove the superseded function use, if reasonable.  We will need to be careful of functional changes when switching to the new functions.  `janitor` is downloaded >100k times/month, so breaking changes should be minimized at (almost) all costs.

@sfirke, what are your thoughts?

**Comment by sfirke** [comment]
This all sounds great to me!  I appreciate the thoughtful contributions and the way you are going about it (discussion first) 🙏 

I'd defer to you two on `cli` vs. `rlang` though if you both like the `cli` result better, maybe that's a reason to go in that direction?

Agreed re: swapping out `gather` and `spread` in a non-breaking way.  If doing it in the most straightforward way would result in breaking changes, let's discuss.  In particular if you are talking about changes that result in objects of a different class, there might be room for that between versions if it made sense.  There are few issues open like that, #301 and https://github.com/tidyverse/dplyr/issues/6689 which has the steps to extend dplyr to so that its verbs work on tabyls.

Only other thought is let's go one PR at a time for these to break things into manageable chunks.

**Comment by olivroy** [comment]
> I'd defer to you two on `cli` vs. `rlang` though if you both like the `cli` result better, maybe that's a reason to go in that direction?

@billdenney let me know what you think 
Since dplyr already imports cli, it wouldn't add a dependency to janitor (although it would have to be explicitly put in Imports, but rlang is good too! (having a dep on stringi is "free" since stringr is already there). Although I really like the [inline markup](https://cli.r-lib.org/reference/inline-markup.html) features of cli.
See a [PR](https://github.com/r-lib/styler/pull/1127/files) I made for styler.

Edit: See https://rlang.r-lib.org/reference/topic-condition-formatting.html?q=abort#enabling-cli-formatting-globally for a solution to avoid explicitly importing cli.


> Only other thought is let's go one PR at a time for these to break things into manageable chunks.

Yes, of course. I will start once the styling PR (#548) is merged! Thanks btw for adding a GitHub action to ensure  consistent styling

**Comment by sfirke** [comment]
#548 is merged!  I'll be curious to see if the auto-styler runs correctly on the next PR.  Maybe leave a trailing space or something to provoke it 😉

**Comment by olivroy** [comment]
So as mentioned in #551, the style action failed when I added a commit that was not correctly styled. (since I don't have write access. But that if some code is left "unstyled" at the end of a PR, I assume that when you merge in the main branch, it adds a commit to restyle automatically (which is what is intended,

 It does send a notification !
![image](https://github.com/sfirke/janitor/assets/52606734/5fc81581-2379-40cd-8468-1e1d81251726)

**Comment by olivroy** [comment]
Potential things that could be done too!

* [ ] Delete `index.Rmd` / `index.md`
   * it is a lot like README, and it seems outdated compared to README. (i.e., it contains Travis Build information). It doesn't seem useful to maintain since pkgdown uses README if index.md is not found. [pkgdown doc](https://pkgdown.r-lib.org/reference/build_home.html#home-page)
   * I checked the diff locally, and from my point of view, it doesn't seem worth it to keep it. You can check it yourself.
 
```r 
library(diffviewer) # A r-lib package 
# Will open an html widget in RStudio to visualize the diff.
diffviewer::visual_diff(
  file_old = "index.md",
  file_new = "README.md",
  height = Inf,
  width = "100%"
)
```

* [ ] (Optional) Maybe `dirty_data.xlsx` could be moved (or duplicated to avoid breaking changes, so that it is installed in the package. See https://r-pkgs.org/data.html#sec-data-extdata
  * With that someone could access janitor's dirty_data with `read_excel(system.file("dirty_data.xlsx", "extdata", package = "janitor"))` 
  * It would increase slightly the install size (+13.2kb)

Thanks for letting me experiment a little! I like your package, it is used, and not too complex. Don't feel pressured to answer right away, and let me know if it is too much!

**Comment by billdenney** [comment]
@olivroy, I really appreciate the "let me know if it is too much"!  😄  I don't think it's too much, and you're helping with some beneficial spring cleaning which many packages could benefit from.

For index.Rmd/README, if we can maintain things in one place, I think that is helpful.  So, I'd go for it as long as all the appropriate information is saved from both.  (@sfirke, you have shouldered the load of this type of documentation-- is there anything unique remaining in index.Rmd?)

I'm neutral for the inclusion of `dirty_data.xlsx`.

**Comment by olivroy** [comment]
Thanks for your help on this ! Truly appreciated
